ignoredBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - workerd

onlyBuiltDependencies:
  - '@sentry/cli'
  - better-sqlite3
  - oracledb
